# Generated by Django 5.0.2 on 2024-07-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_a', models.FloatField()),
                ('longitude_a', models.FloatField()),
                ('latitude_b', models.FloatField()),
                ('longitude_b', models.FloatField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
