# Generated by Django 5.0.2 on 2024-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_order_client_remove_order_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('otklonil', 'otklonil')], default='Pending', max_length=20),
        ),
    ]
