# Generated by Django 5.0.2 on 2024-07-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_requests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
