# Generated by Django 5.0.2 on 2024-07-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_delete_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('В ожидании', 'В ожидании'), ('Принял', 'Принял'), ('Отклонил', 'Отклонил')], default='В ожидании', max_length=20),
        ),
    ]
